# Generated by Django 6.0.5 on 2026-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_occasion_alter_booking_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
